### ISSUE TITLE
mk.teratedRFE function isn't found

### ISSUE THREAD

**Issue by epfarias** [kstawiski/OmicSelector#9]
I'm testing some feature selection techniques and the technique Nº 55: iteratedRFECV isn't working, appears the following error:

> Error in mk.iteratedRFE(trainSet = train, testSet = test, classLab = "Class",  : 
>   could not find function "mk.iteratedRFE"

I do not know what to do, i've already looked the github repository and didn't found the function or an way to solute this issue that im reving.

I'll be very happy and thankfull if you guys could help me with this.

Epitácio Farias.

**Comment by kstawiski** [comment]
Thanks for catching this!
It seems that `mk.iteratedRFE` was the old name for the function [`OmicSelector_iteratedRFE`](https://github.com/kstawiski/OmicSelector/blob/master/R/OmicSelector_iteratedRFE.R). I forgot to change the name in `OmicSelector_OmicSelector()` function. Just corrected it - https://github.com/kstawiski/OmicSelector/commit/184bad628ef8ec202469a7f29f24ced5d4eeee43 

As this is a very slow and computationally exhausting method I stopped using it for regular analyses. Maybe @mgkaszkowiak  can optimize it in the future or I will remove it from available methods..

I will test this on new docker images as they will be rebuilt by CI.

Konrad
